/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:494570:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:494570:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:990932:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton2:990932:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:271901:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton3:271901:

public void imgButton4_click1(GImageButton source, GEvent event) { //_CODE_:imgButton4:525454:
  println("imgButton4 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton4:525454:

public void imgButton5_click1(GImageButton source, GEvent event) { //_CODE_:imgButton5:287048:
  println("imgButton5 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton5:287048:

public void imgButton6_click1(GImageButton source, GEvent event) { //_CODE_:imgButton6:502499:
  println("imgButton6 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton6:502499:

public void imgButton7_click1(GImageButton source, GEvent event) { //_CODE_:imgButton7:757862:
  println("imgButton7 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton7:757862:

public void imgButton8_click1(GImageButton source, GEvent event) { //_CODE_:imgButton8:278914:
  println("imgButton8 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton8:278914:

public void imgButton9_click1(GImageButton source, GEvent event) { //_CODE_:imgButton9:872607:
  println("imgButton9 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton9:872607:

public void imgButton10_click1(GImageButton source, GEvent event) { //_CODE_:imgButton10:618908:
  println("imgButton10 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton10:618908:

public void imgButton11_click1(GImageButton source, GEvent event) { //_CODE_:imgButton11:798554:
  println("imgButton11 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton11:798554:

public void imgButton12_click1(GImageButton source, GEvent event) { //_CODE_:imgButton12:787891:
  println("imgButton12 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton12:787891:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  imgButton1 = new GImageButton(this, 32, 96, new String[] { "number 1.png", "number 1.png", "number 1.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 112, 96, new String[] { "number 2.png", "number 2.png", "number 2.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  imgButton3 = new GImageButton(this, 192, 96, new String[] { "number 3.png", "number 3.png", "number 3.png" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  imgButton4 = new GImageButton(this, 32, 176, new String[] { "number 4.png", "number 4.png", "number 4.png" } );
  imgButton4.addEventHandler(this, "imgButton4_click1");
  imgButton5 = new GImageButton(this, 112, 176, new String[] { "number 5.png", "number 5.png", "number 5.png" } );
  imgButton5.addEventHandler(this, "imgButton5_click1");
  imgButton6 = new GImageButton(this, 192, 176, new String[] { "number 6.png", "number 6.png", "number 6.png" } );
  imgButton6.addEventHandler(this, "imgButton6_click1");
  imgButton7 = new GImageButton(this, 32, 256, new String[] { "number 7.png", "number 7.png", "number 7.png" } );
  imgButton7.addEventHandler(this, "imgButton7_click1");
  imgButton8 = new GImageButton(this, 112, 256, new String[] { "number 8.png", "number 8.png", "number 8.png" } );
  imgButton8.addEventHandler(this, "imgButton8_click1");
  imgButton9 = new GImageButton(this, 192, 256, new String[] { "number 9.png", "number 9.png", "number 9.png" } );
  imgButton9.addEventHandler(this, "imgButton9_click1");
  imgButton10 = new GImageButton(this, 32, 336, new String[] { "back.png", "back.png", "back.png" } );
  imgButton10.addEventHandler(this, "imgButton10_click1");
  imgButton11 = new GImageButton(this, 112, 336, new String[] { "number 0.png", "number 0.png", "number 0.png" } );
  imgButton11.addEventHandler(this, "imgButton11_click1");
  imgButton12 = new GImageButton(this, 192, 336, new String[] { "check.png", "check.png", "check.png" } );
  imgButton12.addEventHandler(this, "imgButton12_click1");
}

// Variable declarations 
// autogenerated do not edit
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton imgButton3; 
GImageButton imgButton4; 
GImageButton imgButton5; 
GImageButton imgButton6; 
GImageButton imgButton7; 
GImageButton imgButton8; 
GImageButton imgButton9; 
GImageButton imgButton10; 
GImageButton imgButton11; 
GImageButton imgButton12; 