/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton1:830991:
  println("imgTogButton1 - GImageToggleButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgTogButton1:830991:

public void imgTogButton2_click1(GImageToggleButton source, GEvent event) { //_CODE_:imgTogButton2:601499:
  println("imgTogButton2 - GImageToggleButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgTogButton2:601499:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:449451:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:449451:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, 16, 16, 80, 32);
  label1.setText("My label");
  label1.setOpaque(false);
  label2 = new GLabel(this, 16, 64, 80, 32);
  label2.setText("My label");
  label2.setOpaque(false);
  label3 = new GLabel(this, 16, 112, 80, 32);
  label3.setText("My label");
  label3.setOpaque(false);
  label4 = new GLabel(this, 16, 160, 80, 32);
  label4.setText("My label");
  label4.setOpaque(false);
  label5 = new GLabel(this, 16, 208, 80, 32);
  label5.setText("My label");
  label5.setOpaque(false);
  label6 = new GLabel(this, 16, 256, 80, 32);
  label6.setText("My label");
  label6.setOpaque(false);
  imgTogButton1 = new GImageToggleButton(this, 112, 16, "open_closed.png", 1, 2);
  imgTogButton1.addEventHandler(this, "imgTogButton1_click1");
  imgTogButton2 = new GImageToggleButton(this, 208, 16, "auto_manual.png", 1, 2);
  imgTogButton2.addEventHandler(this, "imgTogButton2_click1");
  button1 = new GButton(this, 16, 400, 64, 64);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GImageToggleButton imgTogButton1; 
GImageToggleButton imgTogButton2; 
GButton button1; 